--1
-- ANNUAL SALARY -> 공백이 있는 ALIAS -> ""로 묶어야함.
SELECT EMPLOYEE_ID, LAST_NAME, SALARY * 12 "ANUAL SALARY"
 FROM employees;

--2
DESC DEPARTMENTS
SELECT * FROM DEPARTMENTS;

--3
DESC employees;
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES;

--4
SELECT LAST_NAME || ', ' || JOB_ID AS "EMPLOYEE AND TITLE"
FROM EMPLOYEES


