--1
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000;

--2
SELECT LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

--3
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;

--------------------------
--4
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE< DATE '2017-02-20'   AND HIRE_DATE < DATE '2017-05-01'
ORDER BY HIRE_DATE;
-------------------

--5
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20, 50) 
ORDER BY LAST_NAME;

--6
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE (SALARY BETWEEN 5000 AND 12000) AND DEPARTMENT_ID IN (20, 50) 
ORDER BY LAST_NAME, department_id;

--7 1994년에입사한모든사원의이름과입사일을표시
SELECT HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN DATE '2014-01-01' AND DATE '2014-12-31';

--8 관리자가없는모든사원의이름과업무ID를표시
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE manager_id IS NULL;

--9 커미션을받는모든사원의이름, 급여및커미션을급여및커미션을기준으로내림차순으로정렬하여표시
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY COMMISSION_PCT DESC;

-- 10 이름의세번째문자가a인모든사원의이름을표시
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%';

--11
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%';

-- 12 무가영업사원(SA_REP)또는사무원(ST_CLERK)이면서급여가$2,500, $3,500 또는$7,000가아닌모든사원의이름, 업무및급여를표시
SELECT LAST_NAME,JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN ('SA_REP', 'ST_CLERK') AND SALARY NOT IN( 2500, 3500, 7000);

-- 12 커미션비율이20%인모든사원의이름, 급여및커미션을표시
SELECT LAST_NAME, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT = 0.2;





--1
SELECT SYSDATE 
FROM DUAL;

--2
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND(SALARY * 1.15) "NEW SALARY"
FROM EMPLOYEES;

--3
SELECT LAST_NAME, LENGTH(LAST_NAME)
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'A%' OR LAST_NAME LIKE 'M%'
ORDER BY LAST_NAME;


--4
SELECT LAST_NAME, ROUND(MONGTHS_BETWEEN(SYSDATE, HIRE_DATE)) "MONTHS_WORKED"
FROM EMPLOYEES
ORDER BY "MONTHS_WORKED";

--5
SELECT LAST_NAME || 'EARN SARARY ' || SALARY || ' MONTHLY BUT WANTS ' || SALARY *3 AS "DREAM SALARY"
FROM EMPLOYEES;


--6
SELECT LAST_NAME, SALARY
FROM EMPLOYEES;

--7 LPAD 



-- 11 CASE, WEHN 

SELECT JOB_ID,
        CASE JOB_ID
        WHEN 'AD_PRES' THEN 'A'
        WHEN 'ST_MAN'  THEN 'B'
        WHEN 'IT_PROG' THEN 'C'
        WHEN 'SA_REP'  THEN 'D'
        ELSE 'E'
        END AS GRADESAA
FROM EMPLOYEES
ORDER BY GRADESAA;
