--1
SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--2
SELECT DISTINCT E.JOB_ID, D.LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.DEPARTMENT_ID = 80;

--3
SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.LOCATION_ID, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE e.department_id = d.department_id AND
d.location_id = l.location_id AND 
E.COMMISSION_PCT IS NOT NULL;

--4
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = d.department_id AND e.last_name LIKE '%a%';


--5
SELECT E.LAST_NAME, E.JOB_ID, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE e.department_id = d.department_id AND
      d.location_id = l.location_id AND
      L.CITY = 'Toronto';

--6
SELECT E.LAST_NAME AS "EMPLOYEE", E.EMPLOYEE_ID AS "EMP#", M.LAST_NAME AS "MANAGER", M.EMPLOYEE_ID
FROM EMPLOYEES E, EMPLOYEES M
WHERE e.manager_id = M.EMPLOYEE_ID(+); -- OUTER JOIN

--7
SELECT E.DEPARTMENT_ID "DEPARTMENT", E.LAST_NAME EMPLOYEE, C.LAST_NAME COLLEAGUE
FROM EMPLOYEES E, EMPLOYEES C
WHERE E.DEPARTMENT_ID = C.DEPARTMENT_ID AND E.EMPLOYEE_ID <> C.EMPLOYEE_ID
ORDER  BY "DEPARTMENT", "EMPLOYEE", "COLLEAGUE";

--8
SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E
WHERE E.HIRE_DATE > (SELECT HIRE_DATE
                        FROM EMPLOYEES
                        WHERE LAST_NAME = 'Davies'
                        )

SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E, EMPLOYEES D
WHERE D.LAST_NAME = 'Davies' AND e.hire_date > D.HIRE_DATE


-- 9


--DESC DEPARTMENTS;
--DESC EMPLOYEES;

